# Generated by Django 3.2.8 on 2021-10-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('clouth', 'clouths'), ('electronic', 'electronics'), ('mobile', 'mobiles')], max_length=100)),
            ],
        ),
    ]
